### ISSUE TITLE
Suggestions are no longer automatically triggered by default as of VS Code 1.11 

### ISSUE THREAD

**Issue by chauger** [andersea/HTMLClassSuggestionsVSCode#9]
Extension does not appear to be working on the latest release of VS Code 1.11 for Mac.

**Comment by andersea** [comment]
Thanks for reporting this. Can you try pressing ctrl+spacebar while inside the quotation marks and see if it opens the suggestions list?

Looks like the behaviour of the text-edit component in vscode changed somehow, so that the heuristics for determining if you are currently inside a class attribute fails. When the heuristic fails, the completion item provider function behaves as if you are not inside a class attribute and thus do not return any suggestions to the editor.

I am somewhat reluctant to make any changes as of now, because this could very well be a bug in vscode. I will investigate if there is any hardening that can be done that will mitigate this change, but not break it again if they change the behaviour again.

**Comment by chauger** [comment]
ctrl+space does work on the PC. I haven't tried on Mac yet. I did need to click on the lightning bolt to have it rebuild the cache and that seemed to take longer than usual, but did eventually get it. I am using bootstrap so that could be the reason for the long time. :) I guess for now I can use the ctrl+space until something gets fixed in the plugin or VS Code. I'll be keeping an eye out for the update. Thanks for the fast reply and looking into the issue. I can't wait to see it functioning as it used to. Great plugin!

**Comment by andersea** [comment]
Thanks. I have had a bit of time to look into this further. The problem seems to be that VS Code no longer asks for completion items while inside the quotation marks. This is very unfortunate because that is exactly where we need the suggestions. It only happens when the language-mode is html (or html-based, like php), so in vue components it is still working.

I can provide a workaround, which is to specifically state a list of trigger characters (a-z) that would cause the completion item function to be called. However my experiments so far indicates that this breaks the build-in provider, so you no longer get completion suggestions for normal html tags like input, div, table, and so forth, so I think this would be bad thing to add.

The next cause of action, I think, would be to file a bug report on VS Code.

**Comment by florianbouvot** [comment]
Same issue for me.
`ctrl` + `space` open the suggestions list off all existing classes in the workspace *(macOS 10.12.4 - VSCode 1.11.1)*.

**Comment by andersea** [comment]
The breakage is due to this wonderful new feature in VS Code:

https://code.visualstudio.com/updates/v1_11#_intellisense-in-comments

Basically for now you have two options:

1. Change the setting "strings" to true as per the above documentation. This reenables the old behaviour.
2. Trigger the suggestions manually with ctrl+space.

I am experimenting with forcing the setting from code, but is not have success with it at the moment.

**Comment by florianbouvot** [comment]
@andersea thanks for your responsiveness.

I change to `"strings": true` in `"editor.quickSuggestions"` and it works as expected 👍

*Your extension as better suggestion result than others I try 😉*

**Comment by andersea** [comment]
I think this one is overdue for a close.
